### PR TITLE
Add support for Fastlane + TestFlight deployment workflow

### PR DESCRIPTION
**Pull request by billybooth**
This PR includes a few changes. The core changes to the Fastfile and the addition of a LoopCaregiver.yml, as well as the addition and integration of the `CAREGIVER_APP_BUNDLE_IDENTIFIER` are contributions from @bjornoleh.

Here is a high-level summary of the changes:
* Added a LoopCaregiver.xcconfig that pulls in the `$(LOOP_DEVELOPMENT_TEAM)` from LoopConfigOverride.xcconfig and uses it as well in the default app bundle ID.
* Added a LoopCaregiver.yml that allows LoopCaregiver to be built and deployed from GH Actions.
* Updated the Fastfile and other workflow YAMLs to provision the LoopCaregiver identifier and certificate.
* Declared use of standard encryption to avoid the need to declare the use of encryption manually in TestFlight.
* Updated testflight.md to include instructions for building LoopCaregiver

This PR contains one **BREAKING CHANGE** for users that have already deployed, either locally or via App Store Connect/TestFlight.  The default BUNDLE ID has now changed from `org.loopkit.LoopCaregiver` to the value of `$(CAREGIVER_APP_BUNDLE_IDENTIFIER)`, which evaluates to `com.${DEVELOPMENT_TEAM}.loopkit.LoopCaregiver` by default. The consequence of this change is that Caregiver users will lose their settings and need to re-add their Loopers unless they change the `$(CAREGIVER_APP_BUNDLE_IDENTIFIER)` to match the old default value or the value of the identifier that they previously pushed to TestFlight.

Let me know if you have any questions!

### CODE REVIEW

**Comment by bjornoleh** [comment]
The intention with this PR is to enable easy cloud builds of both Loop and LoopCaregiver from the same repository and possibly also the same branch, if or when caregiver is merged into LoopKit/LoopWorkspace dev/main. 

The instructions are based on the user forking LoopWorkspace, but GitHub only allows one fork per repository. Hence the LoopCaregiver cloud build will either require the skills of bringing caregiver into their LoopKit-based fork, or they will have to choose to fork either LoopKit or gestrich LoopWorkspace. 

Hopefully, the caregiver branch can be brought into LoopKit/LoopWorkspace soon, and continue its development there until it is ready to be merged with dev (assuming this is the intent for this project).

**Comment by bjornoleh** [comment]
The LoopCaregiver.yml workflow file will also have to be present in the default branch (currently “main” in LoopKit/LoopWorkspace) to allow it to be selected from the Actions tab. So perhaps this file should also be added to main for this to be a viable option for everyone. 

Alternatively, they can be instructed to change their default branch to “caregiver”, if this branch was moved to LoopKit.

**Comment by billybooth** [comment]
@bjornoleh [said](https://github.com/gestrich/LoopWorkspace/pull/12#issuecomment-1402635077):
> The LoopCaregiver.yml workflow file will also have to be present in the default branch (currently “main” in LoopKit/LoopWorkspace) to allow it to be selected from the Actions tab. So perhaps this file should also be added to main for this to be a viable option for everyone.
> 
> Alternatively, they can be instructed to change their default branch to “caregiver”, if this branch was moved to LoopKit.

Yes, ideally this will ultimately land in `LoopKit/LoopWorkspace`'s `main` branch, but for the time-being, I think the best option is for @gestrich to change the default branch of `gestrich/LoopWorkspace` to `caregiver`, since that is the branch people are building Loop Caregiver from, it is currently up-to-date with `LoopKit/LoopWorkspace` `main`, and it will gain the additional workflow when this PR is merged.

I think that people who want to build both Loop and Loop Caregiver using this deployment strategy will be most likely to fork `gestrich/LoopWorkspace` and set up their secrets there for the foreseeable future.

**Comment by bjornoleh** [comment]
Ok, as long as the caregiver branch is even with LoopKit main, then both apps can be cloud built from here. I just noticed that in LoopDocs it is stated that one should not try to build the Loop app from the caregiver branch. But that may not be valid advice now. Tagging @marionbarker regarding LoopDocs.

**Comment by gestrich** [comment]
@billybooth  I switched the default branch in this repo to be "caregiver". I don't have much experience with the Fastlane flow so just let me know when ready to merge and I'll hit the button.

**Comment by gestrich** [comment]
> Ok, as long as the caregiver branch is even with LoopKit main, then both apps can be cloud built from here. I just noticed that in LoopDocs it is stated that one should not try to build the Loop app from the caregiver branch. But that may not be valid advice now. Tagging @marionbarker regarding LoopDocs.

I think the only reason not to build Loop from this repo is it will not be up-to-date with LoopKit's version. It needs manually updated, which I sometimes do, but I wouldn't want a user building an old version of Loop.

**Comment by billybooth** [comment]
@gestrich [said](https://github.com/gestrich/LoopWorkspace/pull/12#issuecomment-1402834644):
> I don't have much experience with the Fastlane flow so just let me know when ready to merge and I'll hit the button.

This is ready to merge now.

**Comment by bjornoleh** [comment]
> > Ok, as long as the caregiver branch is even with LoopKit main, then both apps can be cloud built from here. I just noticed that in LoopDocs it is stated that one should not try to build the Loop app from the caregiver branch. But that may not be valid advice now. Tagging @marionbarker regarding LoopDocs.
> 
> I think the only reason not to build Loop from this repo is it will not be up-to-date with LoopKit's version. It needs manually updated, which I sometimes do, but I wouldn't want a user building an old version of Loop.

I checked a bit, and I notice your caregiver branch is even with dev, not main. That was practically the same a few days ago, but this will change as time goes. 

It would be nice not having to ask people to delete their forks and enter repo secrets all over again. So I have documented a way to bring caregiver into an existing LoopKit fork on ones GitHub page. This would have to be based on loop dev at this point to avoid merge conflicts, which can't be resolved in the GitHub web UI. If the "production branch" of caregiver was based on current main, users could base it off of that and would not have to be exposed to emerging dev bugs.

In a few words, the workflow would be as follows:

- Select the dev branch in personal GitHub LoopWorkspace repository (or "main" if caregiver branch was even with LoopKit main)
- Make sure it is up to date by clicking Sync fork (not possible unless based on the default branch (main) of the parent repository)
- Click the branch drop-down menu, and type "caregiver", and then click **Create branch 'caregiver' from 'dev'** (or 'main')
Skjermbilde 2023-01-25 091524
- Then open a pull request from gestricht to ones own repository. This takes a few clicks and can easily be messed up, but one can also simplify this with a link to edit by entering ones own username:

`https://github.com/[GitHub username]/LoopWorkspace/compare/caregiver...gestrich:LoopWorkspace:caregiver`

After this, change default branch to `caregiver` and follow the instructions.

Ideally, the user would specify building Loop from `main` when doing cloud builds later. Unless caregiver is kept up to date of course. Which isn't a big deal since main does not get frequent releases. The issue would be if dev code is required for caregiver updates later...

Alternatively, one could say that cloud builds of Loop + Loop Caregiver would be based on dev.

All in all, the above is not entirely trivial, but doable. I don't know if LoopCaregiver is ready for some kind or release yet so there could be a split between "production" and development versions (on gestricht or LoopKit), which could alleviate some of the issues above, or if it is to be considered an app in rapid development still.

**Pull request merged**
